# Generated by Django 5.2.8 on 2025-12-31 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('loans', '0002_rename_amount_loan_total_repayment_and_more'),
        ('users', '0002_profile_created_at_profile_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='account',
            field=models.ForeignKey(default=1982, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='accounts.bankaccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(default=1982, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='users.user'),
            preserve_default=False,
        ),
    ]
